### ISSUE TITLE
Выбрать типовую среду разработки

### ISSUE THREAD

**Issue by okoff** [fitophoto/ann#2]
Какая конкретно версия IDE (VS) будет использована?

**Comment by grimkel** [comment]
ide Microsoft Visual Studio Community 2022 17.0.5 (текущая последняя на сайте) + обязательно установить англоязычный языковой пакет.
Используем [libheif](https://github.com/strukturag/libheif), установка при помощи [vcpkg](https://github.com/Microsoft/vcpkg/).
+
Не особо относиться к данной теме, но в libheif уже есть конвертер в пространоство rgb можно использовать его. 
Для проверки корретности перевода сделал конвертер в jpg на скорую руку (там захардкожены пути к файлам, но изменить их несложно). Скинул в test-convert.

**Comment by okoff** [comment]
![image](https://user-images.githubusercontent.com/24369177/151754180-12c823ef-8dd5-42a7-ae6e-d71fda0f158e.png)

https://github.com/fitophoto/ann/tree/main/test-convert

**Comment by okoff** [comment]
![image](https://user-images.githubusercontent.com/24369177/151756895-351f149f-55e7-4b9d-9b1d-e38b0de63c4a.png)

Дополнительны компоненты нужны?

**Comment by grimkel** [comment]
Нет. Я устанавливал только эти компоненты и конвертер компилировался исправно.
